### PR TITLE
fix issues #1039

### PR DESCRIPTION
**Pull request by happyday517**

### CODE REVIEW

**Comment by wendal** [comment]
这整个类替换的节奏,只能reject啊

**Comment by happyday517** [comment]
晕了 明明只改了一点点 不知道为啥识别为所有代码全换了

**Comment by wendal** [comment]
是不是自动format了? 或者写一下怎么修改吧

**Comment by happyday517** [comment]
array2map

    @SuppressWarnings("unchecked")
    public static <T extends Map<K,V>,K,V> T array2map(Class<T> mapClass,
                                                                      Object array,
                                                                      String keyFieldName) {
        if (null == array)
            return null;
        Map<K,V> map = createMap(mapClass);
        int len = Array.getLength(array);
        if (len > 0) {
            V obj = (V) Array.get(array, 0);
            Mirror<?> mirror = Mirror.me(obj.getClass());
            for (int i = 0; i < len; i++) {
                obj = (V) Array.get(array, i);
                K key = (K) mirror.getValue(obj, keyFieldName);
                map.put(key, obj);
            }
        }
        return (T) map;
    }

collection2map

    @SuppressWarnings("unchecked")
    public static <T extends Map<K, V>,K,V> T collection2map(Class<T> mapClass,
                                                                           Collection<?> coll,
                                                                           String keyFieldName) {
        if (null == coll)
            return null;
        Map<K, V> map = createMap(mapClass);
        if (coll.size() > 0) {
            Iterator<?> it = coll.iterator();
            V obj = (V) it.next();
            Mirror<?> mirror = Mirror.me(obj.getClass());
            K key = (K) mirror.getValue(obj, keyFieldName);
            map.put(key, obj);
            for (; it.hasNext();) {
                obj = (V) it.next();
                key = (K) mirror.getValue(obj, keyFieldName);
                map.put(key, obj);
            }
        }
        return (T) map;
    }

createMap:

    @SuppressWarnings("unchecked")
    private static <T extends Map<K, V>,K,V> T createMap(Class<T> mapClass) {
        Map<K,V> map;
        try {
            map = mapClass.newInstance();
        }
        catch (Exception e) {
            map = new HashMap<K,V>();
        }
        if (!mapClass.isAssignableFrom(map.getClass())) {
            throw Lang.makeThrow("Fail to create map [%s]", mapClass.getName());
        }
        return (T) map;
    }

改了这3处,其他没动

**Comment by happyday517** [comment]
你来搞定吧

**Comment by ywjno** [comment]
这种写法在低版本的 jdk 里面也好用么？

**Comment by wendal** [comment]
f29fd34 这样改了

**Comment by wendal** [comment]
e45bf93485acaa35e5abbfe8d7c226380f3e04b8 这个才对

**Pull request closed without merging**
